name: k9i_cli
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/K9i-0/k9i_cli

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  grinder: ^0.9.3

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.0
